name: analysis_eel_data
channels:
  - conda-forge
  - defaults
dependencies:
  - iris
  - numpy
  - palettable
  - jupyter
  - pytest
  - scipy
  - xarray
  - pandas
  - netcdf4
  - seaborn
  - jupyterlab
  - gmt
  - matplotlib
  - nb_conda
  - ipykernel
  - plotly
  - holoviews
  - bokeh
  - hvplot
  - panel
  - voila
  - scikit-image
  - voila-gridstack
