name: analysis_eel_data
channels:
  - conda-forge
  - defaults
dependencies:
   # Required for full project functionality (dont remove)
  - pytest
  # Other (remove and add as needed)
  - nb_conda
  - ipykernel
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - netcdf4
  - pandas
  - matplotlib
  - iris
  - palettable
  - seaborn
  - gmt
  - plotly
  - pyviz::holoviz
  - pyviz::hvplot
  - bokeh
