name: analysis_eel_data
channels:
  - conda-forge
  - defaults
dependencies:
  - palettable
  - matplotlib
  - gmt
  - numpy
  - hvplot
  - pytest
  - xarray
  - netcdf4
  - holoviews
  - bokeh
  - jupyter
  - jupyterlab
  - panel
  - pandas
  - seaborn
  - scipy
  - iris
  - ipykernel
  - nb_conda
  - plotly
